---
name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update recent activity
        uses: jamesgeorge007/github-activity-readme@338f4f82e1476c1519ab946bacba0ff3d8a23b92
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
